# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master # O la rama que uses como principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Permisos necesarios para que la Acción se autentique con Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso de autenticación con Google Cloud usando Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/997758829677/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-action-954993077@expansispro-react.iam.gserviceaccount.com'

      - name: 'Build Project'
        run: npm ci && npm run build

      # Paso de despliegue a Firebase (ya no necesita el secreto)
      - name: 'Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: 'expansispro-react'
